### ISSUE TITLE
cnpm run start报错

### ISSUE THREAD

**Issue by goldEli** [arcthur/react-book-examples#10]
> react-book-examples@ start D:\Work\test\react-book-examples-master\01
> NODE_ENV=development node server.js

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SF2160\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\SF2160\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "start"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-book-examples@ start: `NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-book-examples@ start script 'NODE_ENV=development node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-book-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-book-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-book-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\test\react-book-examples-master\01\npm-debug.log

--------------------------
npm -v  :  2.15.9
cnpm -v : 4.4.2

**Comment by arcthur** [comment]
这个是 window 的问题
先在命令行下 set NODE_ENV=development
再 node server
