### ISSUE TITLE
TabContent代码的疑问

### ISSUE THREAD

**Issue by purelanren** [arcthur/react-book-examples#12]
https://github.com/arcthur/react-book-examples/blob/master/01/js/TabContent.js#L13
* 其中的`isActive `这个props的作用是什么，个人认为这个不是`TabContent`应该关心的props，`TabContent`应该关心`activeIndex `就行了
* 另外下面的`childen.map`中又重新定义了一个命名有冲突的`isActive`，虽然我认为此处才是真正应该得到`isActive`的地方，但命名规范似乎欠妥

**Comment by arcthur** [comment]
这里的 isActive 传下来的确是多余的，下面 isActive 是传给 pane 用的，命令 isActive 应该可以。
谢谢~
