### ISSUE TITLE
343 页， map 缺少 大括号， 可以 提供电子版，给我们这些买正版图书的人嘛？

### ISSUE THREAD

**Issue by jiexishede** [arcthur/react-book-examples#14]

**Comment by arcthur** [comment]
这个问题已勘误，谢谢，电子版应该在这两个月就会有

**Comment by jiexishede** [comment]
请问,勘误在哪里啊?

**Comment by arcthur** [comment]
http://www.ituring.com.cn/book/1898
另外，电子版已经出了

**Comment by jiexishede** [comment]
大神,  买了 正版 纸质 图书,  没想到 有这个意外. 恭喜, 电子版出来了. 还要再买, 我买了正版纸质书不送电子书啊.

**Comment by arcthur** [comment]
并没有送，哈哈~感谢支持

**Comment by jiexishede** [comment]
感谢大神,百忙之中回复, 有勘误就很好了. 问下大神, 我刚看到第二章,公司用 angular ,现在想转 react开新项目. 问下, react 发送服务器请求和服务器交互,看第几章. 除了本书,还有没有别的资料推荐？

.

**Comment by arcthur** [comment]
看 redux，多试多练就行，看官方文档是最好的资料

**Comment by jiexishede** [comment]
感谢, 官方文档,也看 大神的书,相互参考. 谢谢. 大神.
