### ISSUE TITLE
19页图书 代码 问题.

### ISSUE THREAD

**Issue by jiexishede** [arcthur/react-book-examples#15]
http://stackoverflow.com/questions/41340676/reactjs-the-syntaxerror-with-static-defaultprops
ERROR in ./src/app.js Module build failed: SyntaxError: Unexpected token (8:24)

**Comment by arcthur** [comment]
贴在 stackoverflow 里的代码少了一行， const {color, text} = this.props; static 这行保错的话，是babel配置的问题
