### ISSUE TITLE
第五章，点击标题没有跳转到详细页

### ISSUE THREAD

**Issue by hengg** [arcthur/react-book-examples#18]
components/Home/Preview.js line15
this.props.push(`/detail/${id}`);

**Comment by syaivin** [comment]
我买了书，下了源码；npm install 后，执行 npm run start 怎么直接打开 server.js 文件了；什么情况？

**Comment by aircloud** [comment]
我也是遇到这个问题，自己仿照书写了另外一个小例子也有这个问题(https://github.com/aircloud/react-redux-router-demo)

目前已经找到bug，是因为在开发环境下的：configureStore.dev.js 这个文件并没有引入"routerMiddleware"这个中间件，仿照configureStore.prod.js这个文件把它引入，就没有问题了
