### ISSUE TITLE
Mistake in page Fifty-six

### ISSUE THREAD

**Issue by tinyCucumber** [arcthur/react-book-examples#20]
Hi,i am reading your works recently.And i find one mistake in page Fifty-six,in the sample code of Radio an Check Box on line seven,it should be 'this.handleChange = this.handleChange.bind(this);'instead of 'this.handeChange...' Though it is tiny mistake and i hope in next version it will be corrected.And by the way,the book is useful~

**Comment by arcthur** [comment]
thanks all the way!
