### ISSUE TITLE
第7章代码运行打开后页面报错

### ISSUE THREAD

**Issue by kouguopeng** [arcthur/react-book-examples#23]
![image](https://cloud.githubusercontent.com/assets/22540859/22459678/8ab13d20-e7dc-11e6-9a12-a5eb04b50659.png)
![image](https://cloud.githubusercontent.com/assets/22540859/22459692/9544cb30-e7dc-11e6-9fb6-d2b18e073338.png)

**Comment by arcthur** [comment]
页面内容已经显示出来了，请问报错在哪里？
