### ISSUE TITLE
关于bundle.js文件的位置

### ISSUE THREAD

**Issue by njumathdy** [arcthur/react-book-examples#3]
运行server.js后生成的bundle.js文件在哪里？能以文件夹01为例吗？

**Comment by jidanyu** [comment]
请问你是要运行demo 01吗?

**Comment by njumathdy** [comment]
我可以成功运行demo01，我想请问如何修改webpack.config.js文件和server.js文件使得bundle.js文件可以生成在项目目标文件夹中？（ps:最近才接触，完全新人小白，问的问题可能很蠢。。。）

**Comment by arcthur** [comment]
bundle不会生成具体的文件，是在运行时生成的，这是生产环境与开发环境的区别，可以看书中的附录A，有不同的配置的介绍
