### ISSUE TITLE
我在当当网上面买的书籍，发现了52页，和53页存在错误。

### ISSUE THREAD

**Issue by bruce-16** [arcthur/react-book-examples#30]
e.stopPropagation()写成e.preventDefault();
不知道反馈的邮箱是多少，我很多地方找了半天，没有找到邮箱。 也不清楚我是否买到了盗版书籍。

**Comment by bruce-16** [comment]
zz__0123@163.com这是我的邮箱，我可以发送几张图片。

**Comment by arcthur** [comment]
这里的确有问题，在新印次会修正，谢谢
