### ISSUE TITLE
2.1事件系统 中removeEventListener 用法有误

### ISSUE THREAD

**Issue by lixuguang1988** [arcthur/react-book-examples#46]
1. 51页52页53页多处<code>target.removeEventListener('click') </code>来移除上面注册的click方法。
<code>removeEventListener(type, listener, [options|useCapture])</code> 中前两个参数是必选项。
[mdn removeEventListener](https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/removeEventListener)
2. 48页
> 而 HTML事件则需要使用全部小写的属性名(比如onclick)    

HTML并不区分大小 onclick 和onCLICK 是一样的效果

**Comment by arcthur** [comment]
感谢，已勘误
