### ISSUE TITLE
第二个demo里面Tabs.js的componentWillReceiveProps中打错state了，应该是nextProps.defaultActiveIndex

### ISSUE THREAD

**Issue by qzhongyou** [arcthur/react-book-examples#7]
componentWillReceiveProps(nextProps) {
    if ('defaultActiveIndex' in nextProps) {
      this.setState({
        activeIndex: nextProps.defaultActiveIndex,
      });
    }
  }

**Comment by arcthur** [comment]
详见 #1 问题是一样的。这里是特意这么写的
