### ISSUE TITLE
2.6节里用Immutable优化shouldComponentUpdate的例子为什么还要用“!==”比较？

### ISSUE THREAD

**Issue by TanMichael** [arcthur/react-book-examples#8]
你好，
2.6节里用Immutable优化shouldComponentUpdate的例子有点困惑。
书中提到两个Immutable对象的比较是比较内存地址，而例子中比较props和state的代码同时使用了“!==”和Immutable.is方法。

if (thisProps[key] !== nextProps[key] ||
    !is(thisProps[key], nextProps[key])) {
    return true;
}

我的理解是如果thisProps[key]是Immutable对象，很有可能“!==”比较为true，而后面的!is比较为false。这样不就矛盾了吗？结果并没有起到优化效果。
所以我觉得只需要用is方法来比较就可以了啊。

请指点。谢谢

**Comment by qzhongyou** [comment]
is 只是比较两个值是否相等。不用太在意这些问题。

**Comment by arcthur** [comment]
这里是多此一举了~谢谢
